# ─── Debug / crash reporting attributes ──────────────────────────────────────
# Required for readable Sentry stack traces and Play Console crash reports.
# Without these, R8 strips file names and line numbers from the bytecode.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Required for Ktor/kotlinx.serialization TypeInfo resolution and Kotlin
# generics reflection (body<T>(), Json.decodeFromString<T>()).
-keepattributes Signature

# Keep checked exception metadata used by some AndroidX and Ktor internals.
-keepattributes Exceptions

# ─── kotlinx.serialization ───────────────────────────────────────────────────
# Keep @Serializable annotated classes and their companion objects
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-dontwarn kotlinx.serialization.**

-keep @kotlinx.serialization.Serializable class * {
    *;
}

# Keep serializer companion objects
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion *;
}

# Keep serializer() functions generated by the plugin
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$serializer *;
}

# Keep the kotlinx.serialization infrastructure itself
-keep class kotlinx.serialization.** { *; }
-keep class kotlinx.serialization.internal.** { *; }


# ─── Ktor ─────────────────────────────────────────────────────────────────────
-dontwarn io.ktor.**
-keep class io.ktor.** { *; }
-keep class io.ktor.client.** { *; }
-keep class io.ktor.client.engine.** { *; }
-keep class io.ktor.client.plugins.** { *; }
-keep class io.ktor.http.** { *; }
-keep class io.ktor.utils.** { *; }
-keep class io.ktor.serialization.** { *; }


# ─── Koin ─────────────────────────────────────────────────────────────────────
-dontwarn org.koin.**
-keep class org.koin.** { *; }
-keep class org.koin.core.** { *; }
-keep class org.koin.android.** { *; }

# Keep classes annotated with @KoinInternalApi or that define Koin modules
-keepclassmembers class * {
    org.koin.core.module.Module *;
}

# Keep module-defining extension functions (top-level module { } lambdas)
-keepclassmembers class * {
    public static final org.koin.core.module.Module *;
}


# ─── Domain models ────────────────────────────────────────────────────────────
-keep class com.example.hop.domain.model.** { *; }
