export enum ApiErrorCode {
  // ── Auth ────────────────────────────────────────────────────────────────────
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_INVALID = 'TOKEN_INVALID',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  ADMIN_REQUIRED = 'ADMIN_REQUIRED',

  // ── Validation ──────────────────────────────────────────────────────────────
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_PARAM = 'INVALID_PARAM',

  // ── Resource not found ──────────────────────────────────────────────────────
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TRIP_NOT_FOUND = 'TRIP_NOT_FOUND',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  PLACE_NOT_FOUND = 'PLACE_NOT_FOUND',
  CAR_NOT_FOUND = 'CAR_NOT_FOUND',
  LICENCE_NOT_FOUND = 'LICENCE_NOT_FOUND',
  ALERT_NOT_FOUND = 'ALERT_NOT_FOUND',

  // ── Access ──────────────────────────────────────────────────────────────────
  NOT_YOUR_TRIP = 'NOT_YOUR_TRIP',
  NOT_A_PARTICIPANT = 'NOT_A_PARTICIPANT',
  NOT_A_PARTY = 'NOT_A_PARTY',
  DRIVER_ONLY = 'DRIVER_ONLY',

  // ── Business rules ───────────────────────────────────────────────────────────
  TRIP_NOT_ACTIVE = 'TRIP_NOT_ACTIVE',
  CANNOT_BOOK_OWN_TRIP = 'CANNOT_BOOK_OWN_TRIP',
  INSUFFICIENT_SEATS = 'INSUFFICIENT_SEATS',
  ALREADY_BOOKED = 'ALREADY_BOOKED',
  BOOKING_NOT_PENDING = 'BOOKING_NOT_PENDING',
  ALREADY_CANCELLED = 'ALREADY_CANCELLED',
  TRIP_ALREADY_CANCELLED = 'TRIP_ALREADY_CANCELLED',
  MOBILEPAY_MISSING = 'MOBILEPAY_MISSING',
  TRIP_NOT_ACTIVE_FOR_COMPLETE = 'TRIP_NOT_ACTIVE_FOR_COMPLETE',
  TRIP_HAS_BOOKINGS = 'TRIP_HAS_BOOKINGS',
  ALERT_ALREADY_EXISTS = 'ALERT_ALREADY_EXISTS',
  MODEL_B_MISSING_MIN_PASSENGERS = 'MODEL_B_MISSING_MIN_PASSENGERS',
  MODEL_B_MISSING_DEADLINE = 'MODEL_B_MISSING_DEADLINE',
  MODEL_B_DEADLINE_AFTER_DEPARTURE = 'MODEL_B_DEADLINE_AFTER_DEPARTURE',
  MODEL_A_MISSING_RECURRING_DAYS = 'MODEL_A_MISSING_RECURRING_DAYS',
  NO_OCCURRENCES = 'NO_OCCURRENCES',
  GEOCODING_NOT_CONFIGURED = 'GEOCODING_NOT_CONFIGURED',
  GEOCODING_FAILED = 'GEOCODING_FAILED',
  GEOCODING_NO_RESULT = 'GEOCODING_NO_RESULT',
  ROUTE_NOT_CONFIGURED = 'ROUTE_NOT_CONFIGURED',
  ROUTE_PARAMS_MISSING = 'ROUTE_PARAMS_MISSING',

  // ── Conflict ────────────────────────────────────────────────────────────────
  PHONE_TAKEN = 'PHONE_TAKEN',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  FIELD_TAKEN = 'FIELD_TAKEN',

  // ── Rate limiting ─────────────────────────────────────────────────────────
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // ── Server ──────────────────────────────────────────────────────────────────
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DANGLING_AUTH_USER = 'DANGLING_AUTH_USER',
}
